### PR TITLE
Fix scrollable bug with deprecated .size()

### PR DESCRIPTION
**Pull request by alexitaylor**
### Description 

The .size() method is deprecated as of jQuery 1.8, replaced with .length property instead.

Fixes [JARVIS-1514](https://jira.rallyhealth.com/browse/JARVIS-1514).

@AudaxHealthInc/teamjarvis

### CODE REVIEW

**Comment by scottrice10** [comment]
Holy moly this is an old repo. @alexitaylor, please add a repoman file to this repo. Also, follow https://wiki.audaxhealth.com/display/~erik.innocent/How+to+Find+the+Admin+of+a+GitHub+Repository to figure out who the admin of this repo is, and reach out to them to grant write access to teamjarvis so our approvals count.

@usufruct99 this repo does not yet have a repoman, so it has not been added yet to https://docs.google.com/spreadsheets/d/1KpvJxak5EyilHP73tnF2ADfaeFHE6CWaEPR7hoVGQ24/edit#gid=0, heads up.

**Comment by usufruct99** [comment]
The list at that gdoc does not require repoman.  There are just no admins so it doesn't show up on the list at all.

**Comment by anottestad** [comment]
@kirkhoff

**Comment by kflemons** [comment]
@vincentbarranco  do you happen to have write here?

**Comment by vincentbarranco** [comment]
@kflemons Nope. Check with @kirkhoff or one of our Rally super admins.

**Comment by scottrice10** [comment]
@usufruct99 Are you a super admin on this repo? If so, can you make AudaxHealthInc/engage-tech-leads admins here?

**Comment by usufruct99** [comment]
done

**Pull request merged**
